# Generated by Django 4.0.2 on 2022-04-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='describe',
            new_name='description',
        ),
    ]
