# Generated by Django 4.0.2 on 2022-04-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0002_rename_describe_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=224)),
                ('description', models.TextField(max_length=254)),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
